import os
import logging
import toml

logger = logging.getLogger(__name__)

CONTEXT_INFO_USAGE_INSTRUCTION = """
You will receive supplemental context for the current task. Use it to better understand the issue and to localize the relevant code more accurately.

Treat this context as additional evidence, not as the final answer.
- It may contain noise.
- It may be incomplete.
- You should carefully analyze it and decide how to use it when searching for relevant code locations.

Depending on the settings, the supplemental context may include:
1. Unique artifacts
2. Unique dependency tree

## How to use this supplemental context
- Use it to identify candidate files, classes, functions, and execution paths that may be relevant to the issue.
- Cross-check it against the issue description and the repository evidence you collect.
- Do not assume every artifact is important.
- Do not assume the provided context is sufficient by itself.

## What the provided information means
Assume the issue sent to you is a feature request requesting feature F.

1. Unique artifacts
- The unique artifacts are obtained through a Software Reconnaissance-style analysis.
- For the requested feature described in the issue text, two Python scripts, A.py and B.py, describing the same process are executed and traced.
- The only difference is that A.py is executed with feature F enabled, while B.py is executed with the feature disabled.
- By comparing the two tracing results, the overlapping part between the trace for A.py and B.py is subtracted.
- The remaining artifacts are the unique artifacts that appear only in A.py.
- These unique artifacts are likely to be related to the feature and thus to the issue.

2. Unique dependency tree
- The unique dependency tree is obtained by further analyzing the data dependencies of the unique artifacts.
- It contains the dataflows associated with the unique artifacts.
- It can help you understand how the unique artifacts are related to each other and how they are related to other parts of the codebase.
"""


TRACE_TOOL_USAGE_INSTRUCTION = """
Supplemental DaLIC evidence is available through tools for this instance.

Suggested workflow:
- At the beginning of analyzing a new data point, first inspect the raw execution-trace evidence with `get_trace_artifacts`.
- During the analysis, you may call `get_trace_artifacts` again with narrower filters such as `path_contains` or `name_contains`.
- When available, use `get_trace_data_dependencies` whenever you need a more precise dataflow slice around a traced symbol, scope, or file path.
- You can revisit these tools at any point in the investigation; they are not only for the beginning.
- Treat these tool outputs as compact raw evidence and verify them with the regular repository tools before finishing.
"""


TRACE_FOLLOWUP_REMINDER = """
DaLIC raw evidence tools remain available throughout the investigation.
If your current evidence is too broad or incomplete, call `get_trace_artifacts` or `get_trace_data_dependencies` again with more precise filters before finishing.
"""

def build_instance_dalic_info_prompt(with_data_deps: bool = False, instance_id: str = None) -> str:
    """Build a prompt that provides information about the current instance to the agent.

    This prompt is used to inform the agent about the DaLIC generated context of the user's task,
    The context will include dynamic tracing results generated by DaLIC: the substracted tracing information in file "unique_artifacts.txt"
    including any relevant data dependencies if `with_data_deps` is set to True. the data dependencies information is in file "uniques_dep_tree_edge_list.txt"

    Args:
        with_data_deps (bool): Whether to include information about data dependencies in the prompt.
        instance_id (str): The ID of the instance for which to build the prompt.

    Returns:
        str: The constructed prompt containing instance information.
    """
    message = ""

    folder_path = os.path.dirname(__file__)
    txt_source_folder = os.path.join(folder_path, "vt_results", instance_id)
    unique_artifacts = ""
    data_deps = ""
    unique_artifacts_path = os.path.join(txt_source_folder, "unique_artifacts.txt")
    data_deps_path = os.path.join(txt_source_folder, "unique_dep_tree_edgelist.txt")
    if os.path.exists(unique_artifacts_path):
        with open(unique_artifacts_path, "r") as f:
            unique_artifacts = f.read()
    else:
        raise FileNotFoundError(f"unique_artifacts.txt not found for instance_id: {instance_id}, file path: {unique_artifacts_path}")
    
    if with_data_deps:
        if os.path.exists(data_deps_path):
            with open(data_deps_path, "r") as f:
                data_deps = f.read()
        else:
            raise FileNotFoundError(f"unique_dep_tree_edge_list.txt not found for instance_id: {instance_id}, file path: {data_deps_path}")
        
    # Construct the prompt message
    message = CONTEXT_INFO_USAGE_INSTRUCTION
    message += "\n\nHere is the information about the current task:\n"
    message += "1. Unique artifacts (obtained through Software Reconnaissance-style analysis):\n"
    message += unique_artifacts
    
    if with_data_deps and data_deps:
        message += "\n\n2. Unique dependency tree (dataflows associated with unique artifacts):\n"
        message += data_deps
    
    return message


def build_dalic_tool_usage_prompt(
    use_trace_artifact_tool: bool = False,
    use_trace_data_dependency_tool: bool = False,
) -> str:
    if not use_trace_artifact_tool and not use_trace_data_dependency_tool:
        return ""

    message = TRACE_TOOL_USAGE_INSTRUCTION.strip()
    if not use_trace_artifact_tool:
        message = message.replace(
            "- At the beginning of analyzing a new data point, first inspect the raw execution-trace evidence with `get_trace_artifacts`.\n",
            "",
        )
        message = message.replace(
            "- During the analysis, you may call `get_trace_artifacts` again with narrower filters such as `path_contains` or `name_contains`.\n",
            "",
        )
    if not use_trace_data_dependency_tool:
        message = message.replace(
            "- When available, use `get_trace_data_dependencies` whenever you need a more precise dataflow slice around a traced symbol, scope, or file path.\n",
            "",
        )
    return "\n\n" + message


def build_dalic_tool_followup_reminder(
    use_trace_artifact_tool: bool = False,
    use_trace_data_dependency_tool: bool = False,
) -> str:
    if not use_trace_artifact_tool and not use_trace_data_dependency_tool:
        return ""
    reminder = TRACE_FOLLOWUP_REMINDER.strip()
    if not use_trace_data_dependency_tool:
        reminder = reminder.replace(
            "`get_trace_artifacts` or `get_trace_data_dependencies`",
            "`get_trace_artifacts`",
        )
    return reminder


def calculate_prompt_context_size(prompt: str, model: str = "gpt-4o", verbose: bool = False) -> dict:
    """Calculate the context size (token count) of a prompt.
    
    This function estimates or calculates the exact number of tokens a prompt will consume
    on a given LLM model, and returns the result in both token count and human-readable formats.
    
    Args:
        prompt (str): The prompt text to analyze.
        model (str): The model name to calculate tokens for. Defaults to "gpt-4o".
                    Supports "gpt-4o", "gpt-4", "gpt-3.5-turbo", "claude", etc.
        verbose (bool): Whether to log the result. Defaults to True.
    
    Returns:
        dict: A dictionary containing:
            - 'token_count': Number of tokens
            - 'readable_size': Human-readable format (e.g., "12.5K", "1.2M")
            - 'characters': Character count
            - 'bytes': Byte size (UTF-8 encoded)
            - 'model': The model used for calculation
            - 'estimated': Whether the calculation is estimated (True) or exact (False)
    
    Example:
        >>> result = calculate_prompt_context_size(prompt, model="gpt-4o")
        >>> print(f"Token count: {result['token_count']}")
        >>> print(f"Readable size: {result['readable_size']}")
    """
    result = {
        'characters': len(prompt),
        'bytes': len(prompt.encode('utf-8')),
        'model': model,
        'estimated': True
    }
    
    # Try to use tiktoken for exact calculation if available
    try:
        import tiktoken
        
        # Map model names to tiktoken encoding
        encoding_name = "cl100k_base"  # Default for gpt-4, gpt-4o, gpt-3.5-turbo
        if "gpt-4" in model.lower() or "gpt-3.5" in model.lower() or "gpt-4o" in model.lower():
            encoding_name = "cl100k_base"
        elif "gpt-2" in model.lower():
            encoding_name = "gpt2"
        
        encoding = tiktoken.get_encoding(encoding_name)
        token_count = len(encoding.encode(prompt))
        result['estimated'] = False
        result['token_count'] = token_count
        
    except ImportError:
        # Fallback to estimation: approximately 1 token per 4 characters
        # This is a rough estimate and varies by model and content
        result['token_count'] = len(prompt) // 4
        result['estimated'] = True
        if verbose:
            logger.warning("tiktoken not found. Using rough estimation (1 token ≈ 4 characters)")
    except Exception as e:
        # Another fallback: rough estimation
        result['token_count'] = len(prompt) // 4
        result['estimated'] = True
        if verbose:
            logger.warning(f"Error calculating exact tokens: {e}. Using estimation.")
    
    # Calculate readable size
    token_count = result['token_count']
    if token_count >= 1_000_000:
        result['readable_size'] = f"{token_count / 1_000_000:.1f}M tokens"
    elif token_count >= 1_000:
        result['readable_size'] = f"{token_count / 1_000:.1f}K tokens"
    else:
        result['readable_size'] = f"{token_count} tokens"
    
    # Log if verbose
    if verbose:
        estimation_note = " (estimated)" if result['estimated'] else ""
        logger.info(f"Prompt context size: {result['readable_size']}{estimation_note} | "
                   f"Characters: {result['characters']} | "
                   f"Bytes: {result['bytes']} | "
                   f"Model: {model}")
    
    return result


    
if __name__ == "__main__":
    # Example usage
    toml_file_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), "config.toml")
    instance_id = []

    with open(toml_file_path, 'r') as file:
        data = toml.load(file)
        instance_id = data["selected_ids"]

    num=0
    for instance_id in instance_id:
        print(f"\n{num}============={instance_id}=============")
        num+=1
        # Build and print the prompt
        try:
            prompt = build_instance_dalic_info_prompt(with_data_deps=True, instance_id=instance_id)
            size_info = calculate_prompt_context_size(prompt, model="gpt-4o")
            print(f"\nDetailed breakdown:")
            print(f"  - Token count: {size_info['token_count']}")
            print(f"  - Readable size: {size_info['readable_size']}")
            print(f"  - Character count: {size_info['characters']}")
            print(f"  - Byte size: {size_info['bytes']}")
            print(f"  - Calculation method: {'Exact (tiktoken)' if not size_info['estimated'] else 'Estimated'}")
            
        except FileNotFoundError as e:
            print(f"Error: {e}")
            print("Make sure the instance_id exists in vt_results folder.")
